config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "/", to: "welcome#root", as: 'root'
  get("/home", to: "welcome#home")
  get("/museum", to: "welcome#museum")

  resources :arts do
  resources :likes, shallow: true, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get :liked, on: :collection
  end


  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

 # (namespace decorates path) add PATH before arts like api/v1/arts  | api/v1/arts/:id
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :arts
    end
  end

end

app/models/art.rb
class Art < ApplicationRecord
  
  has_one_attached :image
  has_many(:comments, dependent: :destroy)
  belongs_to :user

  has_many(:likes,  dependent: :destroy) 
  has_many :likers, through: :likes, source: :user

  def self.all_with_comment_counts
    self.left_outer_joins(:comments)
        .select("arts.*", "COUNT(comments.*) AS comments_count")
        .group("arts.id")
      # https://edgeguides.rubyonrails.org/active_record_querying.html#left-outer-joins
end

end

app/controllers/api/v1/arts_controller.rb
class Api::V1::ArtsController < ApplicationController
 #API return just data we dont need to define new method 
 #here because new method return html form page
    def index
        #curl http://localhost:3000/api/v1/arts
        arts = Art.order(created_at: :desc)
        render(json: arts, each_serializer: ArtCollectionSerializer)
    end

    def show
        #curl http://localhost:3000/api/v1/arts/:id
        art = Art.find(params[:id])
        render(json: art)
    end


    def create
    end

    def destroy
    end

end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize!, only: [:edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all.all_with_comment_counts.order('updated_at DESC')
  # curl -H "Accept: application/json" http://localhost:3000/arts
    respond_to do |format|
      format.html {render}
      format.json {render json: @arts}
    end
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
    @comment = Comment.new
    @comments = @art.comments.order(created_at: :desc)
    #show the likes inside the arts so we need to find the users who 
    #like the arts and save it in @like variable
    @like = @art.likes.find_by(user: current_user)
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end


  def liked
    # all the art that this particular logged in user has liked
    @arts = current_user.liked_arts.all_with_comment_counts.order(created_at: :desc)
   
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)
    @art.user = current_user
    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to art_path(@art), notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def art_params
      params.require(:art).permit(:title, :description, :image)
    end

    def authorize!
      redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @art)
  end
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/views/arts/_form.html.erb
<%= form_with(model: art, local: true) do |form| %>
  <% if art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
        <% art.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="container my-5" style="width:800px">
      <div class="form_group my-2 text-white">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form_group my-2 text-white">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form_group my-2 text-white">
        <i class="fas fa-paperclip mr-2"></i><%= form.label :image, for: "exampleFormControlFile1"%>
        <%= form.file_field :image, class: 'form-control-file', id: "exampleFormControlFile1" %>
      </div>

      <div class="form_group my-4">
        <%= form.submit    class: 'btn btn-primary' %>
        <%= link_to 'Back', arts_path, class: 'btn btn-primary mx-2' %>
      </div>

    </div>
  <% end %>

app/views/arts/_list.html.erb
<div class="container">
<h2 class="text-font text-white ml-4">Search By Name</h2>
        <input class="ml-4" id="search-text" type="text" placeholder="Giselle">
</div>

<div class="first container">
  <div class="row justify-content-around">
     <% @arts.each do |art| %>
        <div class="card  col-md-5 mx-2 my-2">
          <%= image_tag art.image.variant(resize: '500X500'), class: 'card-img-top mt-3 d-none d-md-block' if art.image.attached? %>
            <div class="card-body">
               <h5 class="card-title"><%= art.title.truncate(50) %></h5>
                <p class="card-text"><%= art.description.truncate(30) %></p>
                <p class="text-muted"><strong><%= art.user.full_name %></strong></p>
                 <div class="">
                   <%= link_to 'Read More', art, class: 'btn btn-primary mb-2' %>
                   <% if art.comments_count %>
                   <button type="button" class="btn btn-warning right ">
                           <i class="fas fa-comment-dots"></i><span class="ml-2 badge badge-light"><%= art.comments_count %></span></button>
                   <% end %>
                   <button type="button" class="btn btn-danger right d-none d-md-block mr-2">
                      <i class="fas fa-heart"></i><span class="ml-2 badge badge-light"><%= art.likes.count %></span></button>
                 </div>
            </div>
        </div>
    <% end %>
  </div>
</div>





<script>

   function fillter (obj, searchPhrase){
     return  obj.children[1].children[2].innerText.toLowerCase().includes(searchPhrase.toLowerCase())
   }


  const cards = document.querySelectorAll('.card')


  const renderCards = function (cards, searchPhrase) {
    cards.forEach(function (card) {
       // # console.dir(card)
      card.classList.remove('d-none')
      if (! fillter(card, searchPhrase)) {
       card.classList.add('d-none')
      }
    })
  }

  document.querySelector('#search-text').addEventListener('input', function (e) {
    const searchPhrase = e.target.value
    renderCards(cards, searchPhrase)
})

</script>




<style media="screen">
  body {
    background: #41295a;
    background: -webkit-linear-gradient(to right, #2F0743, #41295a);
    background: linear-gradient(to right, #2F0743, #41295a);

  }

  .container {
    margin-top: 35px;
  }

  .right{
    float: right;
  }

  .first {
      margin-top: 50px;
      margin-bottom: 100px;
  }

  .card-title{
    font-family: Playball;
  }


  .text-font{
      font-family: Playball;
  }

  .fa-comment-dots {
    color: white;
  }

</style>

app/views/arts/edit.html.erb
<div class="container text-center">
  <h1>Edit</h1>
</div>

<%= render 'form', art: @art %>



<style media="screen">
  body {
    background: #000428;
    background: -webkit-linear-gradient(to right, #004e92, #000428);
    background: linear-gradient(to right, #004e92, #000428);
  }

  h1 {
    font-family: Playball;
    font-size: 72px;
    background: -webkit-linear-gradient(#eee, #333);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }


.container {
  margin-top: 100px;
}
</style>

app/views/arts/index.html.erb
<div class="container mt-3 mb-3">
   <p class="text-center" id="notice"><%= notice %></p>
</div>
<%= render 'list' %>



<style media="screen">

.text-center {
  font-family: Playball;
  font-size: 30px;
  background: -webkit-linear-gradient(#eee, #333);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

</style>

app/views/arts/liked.html.erb
<div class="container text-center">
<h1>Favourite Arts</h1>
</div>



<%= render 'list' %>






<style media="screen">
  body {
    background: #8E0E00;
    background: -webkit-linear-gradient(to right, #1F1C18, #8E0E00);
    background: linear-gradient(to right, #1F1C18, #8E0E00);

  }

  h1 {
    font-family: Playball;
    font-size: 72px;
    background: -webkit-linear-gradient(#eee, #333);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }

.container {
  margin-top: 100px;
}
</style>

app/views/arts/new.html.erb
<div class="container text-center">
  <h1>Create Your Arts</h1>
</div>

<%= render 'form', art: @art %>



<style media="screen">
  body {
    background: #948E99;
    background: -webkit-linear-gradient(to right, #2E1437, #948E99);
    background: linear-gradient(to right, #2E1437, #948E99);
  }
  .container{
  margin-top: 100px;
  }


h1 {
  font-family: Playball;
  font-size: 72px;
  background: -webkit-linear-gradient(#eee, #333);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}


</style>

app/views/arts/show.html.erb
<div class="container mt-3">
   <p class="text-center" id="notice"><%= notice %></p>
</div>

<div class="container mt-5 mb-5">
<div class="card mb-3 p-3">
  <%= image_tag @art.image.variant(resize: '600X600'),  style:'width:100%; height:100%', class: "card-img-top"  if @art.image.attached? %>
  <div class="card-body">
    <h5 class="card-title"><%= @art.title %></h5>
    <p class="card-text"><%= @art.description %></p>
    <p class="card-text"><small class="text-muted"><%= @art.created_at %></small></p>
    <p class="text-muted">Painted By <strong><%= @art.user.full_name %></strong></p>
    <% if can? :crud, @art %>
      <%= link_to 'Delete', @art, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mr-2', id:'delete'%>
      <%= link_to 'Edit', edit_art_path(@art), class: 'btn btn-primary mr-2' %>
    <% end %>
    <%= link_to 'Back', arts_path,  class: 'btn btn-primary mr-2' %>
    <% if @like.present? %>
       <%= link_to 'Unlike', like_path(@like), method: :delete,  class: 'liked btn btn-info mr-2' %>
    <% else %>
        <%= link_to 'Like',  art_likes_path(@art), method: :post, class: 'liked btn btn-info mr-2' %>
    <% end %>
  </div>
</div>
</div>

<div class="container mb-3">
  <%= form_with(model: [@art, @comment], local: true) do |f| %>
      <% if @comment.errors.any? %>
          <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                  <li class="text-danger"><%= msg %></li>
              <% end %>
          </ul>
      <% end %>

      <div class="form-group">
         <%= f.text_area(
             :body,
             cols: 50,
             rows: 5,
             placeholder: "What are your thoughts?",
             class: "form-control"
         )%>
      </div>

      <%= f.submit "Post", class: "btn-success btn-lg" %>
  <% end %>
</div>


<div class="container mb-5">
  <ul class="list-group answer-list">
    <%  @comments.each do |comment| %>
        <li class="list-group-item mb-2">
            <p>
                <%= comment.body %>
            </p>
            <p>
            <small>
               <% if can? :crud, comment %>
              <%= link_to(
                "Delete",
                art_comment_path(@art, comment),
                method: :delete,
                data: {
                    confirm: "Are you sure?"
                },
                class: "btn btn-danger btn-sm mr-2"
            )%>
            <% end %>
            </small>

            <small>
                Posted <%= time_ago_in_words(comment.created_at) %>By <strong><%= comment.user.full_name %></strong>
            </small>
            </p>
        </li>
    <% end %>
  </ul>
</div>



<style media="screen">
  body{
    background: #44A08D;
    background: -webkit-linear-gradient(to right, #093637, #44A08D);
    background: linear-gradient(to right, #093637, #44A08D);

  }

  .liked {
    float: right
  }




  .text-center {
    font-family: Playball;
    font-size: 30px;
    background: -webkit-linear-gradient(#eee, #333);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }


  .card-title{
    font-family: Playball;
    font-size: 30px;
  }



</style>