config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "/", to: "welcome#root", as: 'root'
  get("/home", to: "welcome#home")
  get("/museum", to: "welcome#museum")

  resources :arts do
  resources :likes, shallow: true, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get :liked, on: :collection
  end


  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

 # (namespace decorates path) add PATH before arts like api/v1/arts  | api/v1/arts/:id
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :arts
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Art Gallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>

  </head>

<body>

    <nav id="mainNavbar" class="navbar navbar-expand-lg navbar-dark bg-dark">

     <i class="change fas fa-paint-brush ml-4 d-none d-lg-block"></i><%= link_to 'Art Gallery',
       root_path, class: 'navbar-brand ml-1 mr-5 mt-1'%>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
      aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>

                 <li class="nav-item">
                   <i class="change fas fa-globe-africa mt-3 ml-1 "></i><%= link_to 'Museum', museum_path,
                   class: 'navbar-brand nav-link ml-1'%>
                 </li>

                 <li class="nav-item">
                   <i class="change fas fa-mask mt-3 ml-1"></i><%= link_to 'Arts', arts_path,
                   class: 'navbar-brand nav-link ml-1'%>
                 </li>

                 <li class="nav-item">
                   <i class="change far fa-images mt-3 ml-1"></i><%= link_to 'Create Art', new_art_path,
                   class: 'navbar-brand nav-link ml-1'%>
                 </li>


                  <li class="nav-item">
                    <i class="change fas fa-tape mt-3 ml-1"></i><%= link_to 'API', api_v1_arts_path,
                    class: 'navbar-brand nav-link ml-1'%>
                  </li>

                  <li class="nav-item">
                    <i class="change fas fa-palette"></i><a href="https://giselle-palette-of-colors.herokuapp.com/"
                    class="navbar-brand nav-link mt-2 ml-1">Pallete</a>
                  </li>

                   <li class="nav-item">
                    <i class="change fas fa-power-off mt-3 ml-1"></i><%= link_to "Log Out", session_path,
                    method: :delete, class: 'nav-link navbar-brand ml-1' %>
                  </li>

                <li class="nav-item dropdown">
                   <a class = "nav-link dropdown-toggle mt-1 mr-5" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_user.full_name%></a>
                   <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <%= link_to "Favourite Arts", liked_arts_path,  class: 'dropdown-item' %>
                        <% if current_user.is_admin? %>
                            <%= link_to "Panel", rails_admin_path,  class: 'dropdown-item' %>
                        <% end %>
                   </div>
                </li>
            <% else %>

                <li class="nav-item">
                  <i class="change fas fa-home mt-2 ml-1"></i><%= link_to 'Home', home_path,
                  class: 'navbar-brand nav-link ml-1'%>
                </li>
                  <li class="nav-item">
                   <i class="change fas fa-user-plus mt-2 ml-1"></i><%= link_to 'Sign Up', new_user_path,
                   class: 'navbar-brand nav-link ml-1' %>
                  </li>
                <li class="nav-item ">
                 <i class="change far fa-hand-point-right mt-2 ml-1"></i><%= link_to "Sign In", new_session_path,
                 class: 'navbar-brand nav-link ml-1' %>
                </li>
            <% end %>
          </ul>
      </div>
    </nav>





  <%= yield %>



  </body>
</html>



<style media="screen">


#mainNavbar {
    font-size: 1.2rem;
    font-weight: 100;
}

#mainNavbar {
  margin: 0-auto;
}

#mainNavbar .nav-link {
    color: white;
}

#mainNavbar .nav-link:hover {
    color: red;
    font-size: 1.2rem;
}

#mainNavbar .navbar-brand:hover {
    color: red;
    font-size: 1.3rem;
}


.change {
  color: white
}

.navbar-brand {
  font-family: Playball;
}

.nav-item {
  font-family: Playball;

}

.dropdown-item {
  font-family: Playball;
  font-size: 1.2rem;
  background-color: black;
  color: white;
}

.dropdown-item:hover {
  background-color: black;
  color: red;
}


</style>